/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meeting8Tc;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class RentalToolsParty extends javax.swing.JFrame {
    ControllerToolParty controller=new ControllerToolParty();
    private final DefaultTableModel model;

    /**
     * Creates new form RentalToolsParty
     */
    public RentalToolsParty() {
        initComponents();
        model = (DefaultTableModel) tableRental.getModel();
        model.getDataVector().removeAllElements();
        tableRental.repaint();
        panelTenda.setVisible(false);
        panelStage.setVisible(false);
        panelMeja.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupTenda = new javax.swing.ButtonGroup();
        groupStage = new javax.swing.ButtonGroup();
        groupMeja = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fieldNama = new javax.swing.JTextField();
        fieldAlamat = new javax.swing.JTextField();
        fieldLamaSewa = new javax.swing.JTextField();
        fieldLamaKembali = new javax.swing.JTextField();
        dateDate = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        fieldBiayaSewa = new javax.swing.JTextField();
        fieldDenda = new javax.swing.JTextField();
        fieldDp = new javax.swing.JTextField();
        fieldTotalSewa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        fieldTotalPendapatan = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lblTenda = new javax.swing.JLabel();
        lblStage = new javax.swing.JLabel();
        lblMeja = new javax.swing.JLabel();
        boxTenda = new javax.swing.JCheckBox();
        boxStage = new javax.swing.JCheckBox();
        boxMeja = new javax.swing.JCheckBox();
        panelTenda = new javax.swing.JPanel();
        radio6x6 = new javax.swing.JRadioButton();
        radio10x10 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        fieldHargaTenda = new javax.swing.JTextField();
        panelStage = new javax.swing.JPanel();
        radio4x6 = new javax.swing.JRadioButton();
        radio6x10 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        fieldHargaStage = new javax.swing.JTextField();
        panelMeja = new javax.swing.JPanel();
        radio20set = new javax.swing.JRadioButton();
        radio50set = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        fieldHargaMeja = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRental = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Penyewaan Peralatan Pesta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Penyewa"));

        jLabel1.setText("Nama Penyewa");

        jLabel2.setText("Hari");

        jLabel3.setText("Hari");

        jLabel4.setText("Lama Pengembalian");

        jLabel5.setText("Lama Sewa");

        jLabel6.setText("Alamat");

        jLabel7.setText("Tgl Sewa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(fieldLamaKembali)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldNama)
                                    .addComponent(fieldLamaSewa)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(fieldAlamat)
                                    .addComponent(dateDate, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldLamaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldLamaKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pembayaran"));

        jLabel14.setText("Biaya Sewa");

        lb.setText("Denda");

        jLabel16.setText("DP");

        jLabel17.setText("Total Sewa");

        fieldDp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldDpKeyReleased(evt);
            }
        });

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Total Pendapatan");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fieldBiayaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldDenda)
                                    .addComponent(fieldDp)
                                    .addComponent(fieldTotalSewa, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))
                            .addComponent(jLabel14)
                            .addComponent(lb)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(fieldTotalPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 13, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldBiayaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldDenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldDp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldTotalSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldTotalPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Peralatan Pesta"));

        boxTenda.setText("Tenda");
        boxTenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTendaActionPerformed(evt);
            }
        });

        boxStage.setText("Stage");
        boxStage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxStageActionPerformed(evt);
            }
        });

        boxMeja.setText("Meja - Kursi");
        boxMeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMejaActionPerformed(evt);
            }
        });

        panelTenda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        groupTenda.add(radio6x6);
        radio6x6.setText("Ukuran 6x6");
        radio6x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio6x6ActionPerformed(evt);
            }
        });

        groupTenda.add(radio10x10);
        radio10x10.setText("Ukuran 10x10");
        radio10x10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio10x10ActionPerformed(evt);
            }
        });

        jLabel11.setText("Harga");

        javax.swing.GroupLayout panelTendaLayout = new javax.swing.GroupLayout(panelTenda);
        panelTenda.setLayout(panelTendaLayout);
        panelTendaLayout.setHorizontalGroup(
            panelTendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTendaLayout.createSequentialGroup()
                .addGroup(panelTendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTendaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelTendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio6x6)
                            .addComponent(radio10x10)))
                    .addGroup(panelTendaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panelTendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(fieldHargaTenda, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTendaLayout.setVerticalGroup(
            panelTendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTendaLayout.createSequentialGroup()
                .addComponent(radio6x6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio10x10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldHargaTenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        panelStage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        groupStage.add(radio4x6);
        radio4x6.setText("Ukuran 4x6");
        radio4x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio4x6ActionPerformed(evt);
            }
        });

        groupStage.add(radio6x10);
        radio6x10.setText("Ukuran 6x10");
        radio6x10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio6x10ActionPerformed(evt);
            }
        });

        jLabel12.setText("Harga");

        javax.swing.GroupLayout panelStageLayout = new javax.swing.GroupLayout(panelStage);
        panelStage.setLayout(panelStageLayout);
        panelStageLayout.setHorizontalGroup(
            panelStageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStageLayout.createSequentialGroup()
                .addGroup(panelStageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelStageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelStageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio4x6)
                            .addComponent(radio6x10)))
                    .addGroup(panelStageLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panelStageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(fieldHargaStage, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelStageLayout.setVerticalGroup(
            panelStageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStageLayout.createSequentialGroup()
                .addComponent(radio4x6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio6x10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldHargaStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        panelMeja.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        groupMeja.add(radio20set);
        radio20set.setText("20 set");
        radio20set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio20setActionPerformed(evt);
            }
        });

        groupMeja.add(radio50set);
        radio50set.setText("50 set");
        radio50set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio50setActionPerformed(evt);
            }
        });

        jLabel13.setText("Harga");

        javax.swing.GroupLayout panelMejaLayout = new javax.swing.GroupLayout(panelMeja);
        panelMeja.setLayout(panelMejaLayout);
        panelMejaLayout.setHorizontalGroup(
            panelMejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMejaLayout.createSequentialGroup()
                .addGroup(panelMejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMejaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelMejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio20set)
                            .addComponent(radio50set)))
                    .addGroup(panelMejaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panelMejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(fieldHargaMeja, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMejaLayout.setVerticalGroup(
            panelMejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMejaLayout.createSequentialGroup()
                .addComponent(radio20set)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio50set)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldHargaMeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boxTenda)
                    .addComponent(lblTenda, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelStage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boxStage)
                    .addComponent(lblStage, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boxMeja)
                    .addComponent(panelMeja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMeja, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxTenda)
                    .addComponent(boxStage)
                    .addComponent(boxMeja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStage, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMeja, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        tableRental.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Penyewa", "Peralatan Sewa", "Biaya Sewa", "Denda ", "DP", "Total Bayar", "Sisa Pembayaran"
            }
        ));
        jScrollPane1.setViewportView(tableRental);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   
    private void boxTendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTendaActionPerformed
       controller.ToolParty(fieldLamaSewa, fieldLamaKembali, fieldDenda, groupTenda, groupStage, groupMeja, boxTenda, boxStage, boxMeja, lblTenda, lblStage, lblMeja, panelTenda, panelStage, panelMeja, radio6x6, radio10x10, fieldHargaTenda, fieldHargaStage, fieldHargaMeja, radio4x6, radio6x10, radio20set, radio50set, fieldBiayaSewa);
        
    }//GEN-LAST:event_boxTendaActionPerformed

    private void radio6x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio6x6ActionPerformed
        controller.ToolParty(fieldLamaSewa, fieldLamaKembali, fieldDenda, groupTenda, groupStage, groupMeja, boxTenda, boxStage, boxMeja, lblTenda, lblStage, lblMeja, panelTenda, panelStage, panelMeja, radio6x6, radio10x10, fieldHargaTenda, fieldHargaStage, fieldHargaMeja, radio4x6, radio6x10, radio20set, radio50set, fieldBiayaSewa);
       
    }//GEN-LAST:event_radio6x6ActionPerformed

    private void radio10x10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio10x10ActionPerformed
        controller.ToolParty(fieldLamaSewa, fieldLamaKembali, fieldDenda, groupTenda, groupStage, groupMeja, boxTenda, boxStage, boxMeja, lblTenda, lblStage, lblMeja, panelTenda, panelStage, panelMeja, radio6x6, radio10x10, fieldHargaTenda, fieldHargaStage, fieldHargaMeja, radio4x6, radio6x10, radio20set, radio50set, fieldBiayaSewa);
       
    }//GEN-LAST:event_radio10x10ActionPerformed

    private void boxStageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxStageActionPerformed
        controller.ToolParty(fieldLamaSewa, fieldLamaKembali, fieldDenda, groupTenda, groupStage, groupMeja, boxTenda, boxStage, boxMeja, lblTenda, lblStage, lblMeja, panelTenda, panelStage, panelMeja, radio6x6, radio10x10, fieldHargaTenda, fieldHargaStage, fieldHargaMeja, radio4x6, radio6x10, radio20set, radio50set, fieldBiayaSewa);
       
    }//GEN-LAST:event_boxStageActionPerformed

    private void radio4x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio4x6ActionPerformed
        controller.ToolParty(fieldLamaSewa, fieldLamaKembali, fieldDenda, groupTenda, groupStage, groupMeja, boxTenda, boxStage, boxMeja, lblTenda, lblStage, lblMeja, panelTenda, panelStage, panelMeja, radio6x6, radio10x10, fieldHargaTenda, fieldHargaStage, fieldHargaMeja, radio4x6, radio6x10, radio20set, radio50set, fieldBiayaSewa);
      
    }//GEN-LAST:event_radio4x6ActionPerformed

    private void radio6x10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio6x10ActionPerformed
        controller.ToolParty(fieldLamaSewa, fieldLamaKembali, fieldDenda, groupTenda, groupStage, groupMeja, boxTenda, boxStage, boxMeja, lblTenda, lblStage, lblMeja, panelTenda, panelStage, panelMeja, radio6x6, radio10x10, fieldHargaTenda, fieldHargaStage, fieldHargaMeja, radio4x6, radio6x10, radio20set, radio50set, fieldBiayaSewa);
        
    }//GEN-LAST:event_radio6x10ActionPerformed

    private void boxMejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMejaActionPerformed
        controller.ToolParty(fieldLamaSewa, fieldLamaKembali, fieldDenda, groupTenda, groupStage, groupMeja, boxTenda, boxStage, boxMeja, lblTenda, lblStage, lblMeja, panelTenda, panelStage, panelMeja, radio6x6, radio10x10, fieldHargaTenda, fieldHargaStage, fieldHargaMeja, radio4x6, radio6x10, radio20set, radio50set, fieldBiayaSewa);

    }//GEN-LAST:event_boxMejaActionPerformed

    private void radio20setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio20setActionPerformed
        controller.ToolParty(fieldLamaSewa, fieldLamaKembali, fieldDenda, groupTenda, groupStage, groupMeja, boxTenda, boxStage, boxMeja, lblTenda, lblStage, lblMeja, panelTenda, panelStage, panelMeja, radio6x6, radio10x10, fieldHargaTenda, fieldHargaStage, fieldHargaMeja, radio4x6, radio6x10, radio20set, radio50set, fieldBiayaSewa);
       
    }//GEN-LAST:event_radio20setActionPerformed

    private void radio50setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio50setActionPerformed
        controller.ToolParty(fieldLamaSewa, fieldLamaKembali, fieldDenda, groupTenda, groupStage, groupMeja, boxTenda, boxStage, boxMeja, lblTenda, lblStage, lblMeja, panelTenda, panelStage, panelMeja, radio6x6, radio10x10, fieldHargaTenda, fieldHargaStage, fieldHargaMeja, radio4x6, radio6x10, radio20set, radio50set, fieldBiayaSewa);
        
    }//GEN-LAST:event_radio50setActionPerformed

    private void fieldDpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldDpKeyReleased
        controller.Dp(evt, fieldNama, fieldDp, fieldTotalSewa, fieldTotalPendapatan, tableRental);
    }//GEN-LAST:event_fieldDpKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controller.Clear(fieldTotalPendapatan, fieldNama, fieldAlamat, dateDate, fieldLamaSewa, fieldLamaKembali, fieldDenda, fieldDp, fieldBiayaSewa, fieldTotalSewa, fieldHargaTenda, fieldHargaStage, fieldHargaMeja, groupTenda, groupStage, groupMeja, boxTenda, boxStage, boxMeja, panelTenda, panelStage, panelMeja, lblTenda, lblStage, lblMeja);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentalToolsParty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentalToolsParty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentalToolsParty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentalToolsParty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentalToolsParty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox boxMeja;
    private javax.swing.JCheckBox boxStage;
    private javax.swing.JCheckBox boxTenda;
    private com.toedter.calendar.JDateChooser dateDate;
    private javax.swing.JTextField fieldAlamat;
    private javax.swing.JTextField fieldBiayaSewa;
    private javax.swing.JTextField fieldDenda;
    private javax.swing.JTextField fieldDp;
    private javax.swing.JTextField fieldHargaMeja;
    private javax.swing.JTextField fieldHargaStage;
    private javax.swing.JTextField fieldHargaTenda;
    private javax.swing.JTextField fieldLamaKembali;
    private javax.swing.JTextField fieldLamaSewa;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JTextField fieldTotalPendapatan;
    private javax.swing.JTextField fieldTotalSewa;
    private javax.swing.ButtonGroup groupMeja;
    private javax.swing.ButtonGroup groupStage;
    private javax.swing.ButtonGroup groupTenda;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lblMeja;
    private javax.swing.JLabel lblStage;
    private javax.swing.JLabel lblTenda;
    private javax.swing.JPanel panelMeja;
    private javax.swing.JPanel panelStage;
    private javax.swing.JPanel panelTenda;
    private javax.swing.JRadioButton radio10x10;
    private javax.swing.JRadioButton radio20set;
    private javax.swing.JRadioButton radio4x6;
    private javax.swing.JRadioButton radio50set;
    private javax.swing.JRadioButton radio6x10;
    private javax.swing.JRadioButton radio6x6;
    private javax.swing.JTable tableRental;
    // End of variables declaration//GEN-END:variables
}
