/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meeting4;

import assignmentCollections.Menu;

/**
 *
 * @author user
 */
public class AppPenjualanBunga extends javax.swing.JFrame {

    /**
     * Creates new form AssignmentMeeting4
     */
    public AppPenjualanBunga() {
        initComponents();
        fieldKirim.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupJarak = new javax.swing.ButtonGroup();
        groupBunga = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        radioAnggrek = new javax.swing.JRadioButton();
        radioMawar = new javax.swing.JRadioButton();
        radioSedapMalam = new javax.swing.JRadioButton();
        fieldHarga = new javax.swing.JTextField();
        fieldJmlBeli = new javax.swing.JTextField();
        fieldDiskon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldKirim = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        radio5 = new javax.swing.JRadioButton();
        radio515 = new javax.swing.JRadioButton();
        radio15 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        fieldTotalBayar = new javax.swing.JTextField();
        btnProcess = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        boxKirim = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Aplikasi Penjualan Bunga");

        jLabel2.setText("Nama Bunga ");

        groupBunga.add(radioAnggrek);
        radioAnggrek.setText("Anggrek");
        radioAnggrek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAnggrekActionPerformed(evt);
            }
        });

        groupBunga.add(radioMawar);
        radioMawar.setText("Mawar");
        radioMawar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMawarActionPerformed(evt);
            }
        });

        groupBunga.add(radioSedapMalam);
        radioSedapMalam.setText("Sedap Malam");
        radioSedapMalam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSedapMalamActionPerformed(evt);
            }
        });

        jLabel3.setText("Harga/Bingkai");

        jLabel4.setText("Jumlah Beli");

        jLabel5.setText("Diskon");

        fieldKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldKirimActionPerformed(evt);
            }
        });

        jLabel6.setText("Biaya Kirim");

        jLabel7.setText("Jarak");

        groupJarak.add(radio5);
        radio5.setText("<5 Km");
        radio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio5ActionPerformed(evt);
            }
        });

        groupJarak.add(radio515);
        radio515.setText("5-15 Km");
        radio515.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio515ActionPerformed(evt);
            }
        });

        groupJarak.add(radio15);
        radio15.setText("> 15 Km ");
        radio15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio15ActionPerformed(evt);
            }
        });

        jLabel8.setText("Total Bayar");

        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        jButton2.setText("Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        boxKirim.setText("Kirim");
        boxKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxKirimActionPerformed(evt);
            }
        });

        jLabel9.setText("Meeting 4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioAnggrek)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(btnProcess))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(164, 164, 164)
                                        .addComponent(jButton2)
                                        .addGap(201, 201, 201)
                                        .addComponent(jButton3))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(radioMawar)
                                                    .addGap(30, 30, 30)
                                                    .addComponent(radioSedapMalam))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(fieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(34, 34, 34)
                                                    .addComponent(boxKirim)))
                                            .addGap(18, 36, Short.MAX_VALUE)
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(fieldKirim, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(fieldJmlBeli, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                                .addComponent(fieldDiskon))
                                            .addGap(34, 34, 34)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(radio5)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(radio515)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(radio15))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(fieldTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel9)
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAnggrek)
                    .addComponent(radioMawar)
                    .addComponent(radioSedapMalam))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(fieldKirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxKirim)
                        .addGap(3, 3, 3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldJmlBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(radio5)
                    .addComponent(radio515)
                    .addComponent(radio15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(fieldTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcess)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioAnggrekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAnggrekActionPerformed
        // TODO add your handling code here:
         if(radioAnggrek.isSelected())
         {
            int hAnggrek=10000;
            fieldHarga.setText(Integer.toString(hAnggrek));
         }
         fieldJmlBeli.requestFocus();
    }//GEN-LAST:event_radioAnggrekActionPerformed

    private void fieldKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldKirimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldKirimActionPerformed
        
    private void radioMawarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMawarActionPerformed
        // TODO add your handling code here:
        
       if(radioMawar.isSelected())
       {
            int hMawar=8000;
            fieldHarga.setText(Integer.toString(hMawar));
       }
       fieldJmlBeli.requestFocus();
    }//GEN-LAST:event_radioMawarActionPerformed

    private void radioSedapMalamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSedapMalamActionPerformed
        // TODO add your handling code here:
         if(radioSedapMalam.isSelected())
         {
            int hSedapMalam=5000;
            fieldHarga.setText(Integer.toString(hSedapMalam));
         }
        fieldJmlBeli.requestFocus();
    }//GEN-LAST:event_radioSedapMalamActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
         //untuk pemberian nilai field diskon
        int syarat=300000;
        
        double diskon;
        int jumlahBeli,hargaBunga,biayaKirim;
        hargaBunga=Integer.parseInt(fieldHarga.getText());
        jumlahBeli=Integer.parseInt(fieldJmlBeli.getText());
        biayaKirim=Integer.parseInt(fieldKirim.getText());
        
        int jumlah;//jumlah pembelia bunga
        jumlah=hargaBunga*jumlahBeli;
        
        //jika diskon telah muncul dan jumlah beli diganti maka fieldDiskon akan hilang harga diskonnya
        if(jumlah<syarat)
        {
            fieldDiskon.setText("");
        }
        diskon=0.05*jumlah;
        
        if(jumlah>=syarat)
        {
            
            fieldDiskon.setText(Double.toString(diskon));
            
        }
        //int biaya5,biaya515,biaya15;
        double totalBayar;
        totalBayar=(hargaBunga * jumlahBeli) - diskon + biayaKirim;
        fieldTotalBayar.setText(""+totalBayar);
    }//GEN-LAST:event_btnProcessActionPerformed
    int biaya5,biaya515,biaya15;
    private void radio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio5ActionPerformed
        // TODO add your handling code here:
        if(boxKirim.isSelected() && radio5.isSelected())
        {
            biaya5=0;
            fieldKirim.setText(Integer.toString(biaya5));
            btnProcess.requestFocus();
        }//else{fieldKirim.setText("");}
        
       
    }//GEN-LAST:event_radio5ActionPerformed

    private void radio515ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio515ActionPerformed
        // TODO add your handling code here:
        if(boxKirim.isSelected() && radio515.isSelected())
        {
            biaya515=20000;
            fieldKirim.setText(Integer.toString(biaya515));
            btnProcess.requestFocus();
        }
        
       
             
         
    }//GEN-LAST:event_radio515ActionPerformed

    private void radio15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio15ActionPerformed
        // TODO add your handling code here:
        if(boxKirim.isSelected() && radio15.isSelected())
        {
            biaya15=50000;
            fieldKirim.setText(Integer.toString(biaya15));
            btnProcess.requestFocus();
        }//else{fieldKirim.setText("");}
        
       
    }//GEN-LAST:event_radio15ActionPerformed

    private void boxKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxKirimActionPerformed
        // TODO add your handling code here:
        if(!boxKirim.isSelected())
        {
            fieldKirim.setText("");
        } 
        radio5.requestFocus();
    }//GEN-LAST:event_boxKirimActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        fieldKirim.setText("");
        fieldDiskon.setText("");
        fieldHarga.setText("");
        fieldJmlBeli.setText("");
        fieldTotalBayar.setText("");
        groupBunga.clearSelection();
        groupJarak.clearSelection();
        boxKirim.setSelected(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Menu menu=new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppPenjualanBunga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppPenjualanBunga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppPenjualanBunga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppPenjualanBunga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppPenjualanBunga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox boxKirim;
    private javax.swing.JButton btnProcess;
    private javax.swing.JTextField fieldDiskon;
    private javax.swing.JTextField fieldHarga;
    private javax.swing.JTextField fieldJmlBeli;
    private javax.swing.JTextField fieldKirim;
    private javax.swing.JTextField fieldTotalBayar;
    private javax.swing.ButtonGroup groupBunga;
    private javax.swing.ButtonGroup groupJarak;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radio15;
    private javax.swing.JRadioButton radio5;
    private javax.swing.JRadioButton radio515;
    private javax.swing.JRadioButton radioAnggrek;
    private javax.swing.JRadioButton radioMawar;
    private javax.swing.JRadioButton radioSedapMalam;
    // End of variables declaration//GEN-END:variables
}
