/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meeting4;

/**
 *
 * @author user
 */
public class RadioCekbox extends javax.swing.JFrame {
    
    /**
     * Creates new form RadioCekbox
     */
    public RadioCekbox() {
        initComponents();
    
    
    
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox3 = new javax.swing.JCheckBox();
        btnGroupPilihan = new javax.swing.ButtonGroup();
        btnGroupData = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radioPilihan1 = new javax.swing.JRadioButton();
        radioPilihan2 = new javax.swing.JRadioButton();
        radioPilihan3 = new javax.swing.JRadioButton();
        radioData1 = new javax.swing.JRadioButton();
        radioData2 = new javax.swing.JRadioButton();
        radioData3 = new javax.swing.JRadioButton();
        btnProcess = new javax.swing.JButton();
        fieldHasil = new javax.swing.JTextField();
        boxPil1 = new javax.swing.JCheckBox();
        box2Pil2 = new javax.swing.JCheckBox();
        fieldPil1 = new javax.swing.JTextField();
        fieldPil2 = new javax.swing.JTextField();
        fieldJumlah = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaHasil = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        jCheckBox3.setText("jCheckBox3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGroupPilihan.add(radioPilihan1);
        radioPilihan1.setText("Pilihan 1");
        radioPilihan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPilihan1ActionPerformed(evt);
            }
        });

        btnGroupPilihan.add(radioPilihan2);
        radioPilihan2.setText("Pilihan 2");
        radioPilihan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPilihan2ActionPerformed(evt);
            }
        });

        btnGroupPilihan.add(radioPilihan3);
        radioPilihan3.setText("Pilihan 3");
        radioPilihan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPilihan3ActionPerformed(evt);
            }
        });

        btnGroupData.add(radioData1);
        radioData1.setText("Data 1");
        radioData1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioData1ActionPerformed(evt);
            }
        });

        btnGroupData.add(radioData2);
        radioData2.setText("Data 2");

        btnGroupData.add(radioData3);
        radioData3.setText("Data 3");

        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        boxPil1.setText("Pil 1");
        boxPil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxPil1ActionPerformed(evt);
            }
        });

        box2Pil2.setText("Pil 2");
        box2Pil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box2Pil2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Jumlah");

        jLabel2.setText("Hasil");

        areaHasil.setColumns(20);
        areaHasil.setRows(5);
        jScrollPane1.setViewportView(areaHasil);

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(47, 47, 47)
                                .addComponent(fieldHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(radioPilihan3)
                                    .addComponent(radioPilihan2)
                                    .addComponent(radioPilihan1))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioData3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radioData1)
                                            .addComponent(radioData2))
                                        .addGap(53, 53, 53)
                                        .addComponent(btnProcess))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boxPil1)
                                    .addComponent(box2Pil2))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldPil2, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(fieldPil1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(fieldJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(radioPilihan1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioPilihan2)
                            .addComponent(radioData2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProcess)
                            .addComponent(radioData1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioPilihan3)
                    .addComponent(radioData3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxPil1)
                    .addComponent(fieldPil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box2Pil2)
                    .addComponent(fieldPil2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void radioPilihan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPilihan3ActionPerformed
        // TODO add your handling code here:
        if(radioPilihan3.isSelected()){
            fieldHasil.setText("Pilihan 3");
            
        }
    }//GEN-LAST:event_radioPilihan3ActionPerformed

    private void radioPilihan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPilihan2ActionPerformed
        // TODO add your handling code here:
        if(radioPilihan2.isSelected()){
            fieldHasil.setText("Pilihan 2");
        }
    }//GEN-LAST:event_radioPilihan2ActionPerformed

    private void radioPilihan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPilihan1ActionPerformed
        // TODO add your handling code here:
        if(radioPilihan1.isSelected()){
            fieldHasil.setText("Pilihan 1");
        }
    }//GEN-LAST:event_radioPilihan1ActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
         
        if(radioData1.isSelected() && radioPilihan1.isSelected()){
            fieldHasil.setText("Pilihan 1 + Data 1");
        }
        if(radioData2.isSelected() && radioPilihan2.isSelected()){
            fieldHasil.setText("Pilihan 1 + Data 2");
        }
        if(radioData3.isSelected() && radioPilihan3.isSelected()){
            fieldHasil.setText("Pilihan 1 + Data 3");
        }
    }//GEN-LAST:event_btnProcessActionPerformed
        int pil1=100;
        int pil2=100;
        int pilihan1;
        int pilihan2; 
        int jumlah;
    private void boxPil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxPil1ActionPerformed
        // TODO add your handling code here:
        
            
        if(boxPil1.isSelected()){
            fieldPil1.setText(Integer.toString(pil1));
            pilihan1=Integer.parseInt(fieldPil1.getText());
            jumlah=pilihan1+pilihan2;
            fieldJumlah.setText(Integer.toString(jumlah));
            
        }else{
            fieldPil1.setText("");
            fieldJumlah.setText("");
        }
    }//GEN-LAST:event_boxPil1ActionPerformed

    private void box2Pil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box2Pil2ActionPerformed
        // TODO add your handling code here:
         
        if(box2Pil2.isSelected()){
            fieldPil2.setText(Integer.toString(pil2));
            pilihan2=Integer.parseInt(fieldPil2.getText());
            jumlah=pilihan1+pilihan2;
            fieldJumlah.setText(Integer.toString(jumlah));
            //Hasil Pilihan \t: \n Pil 1 \t:"+pil1+" \n Pil 2 \t:"+pil2+"  \n Jumlah Nilai CeBox : "+jumlah);
            areaHasil.setText("Hasil Pilihan :\n"+"Pilihan 1 \t :"+fieldPil1.getText()+"\nPilihan 2\t :"+fieldPil2.getText()+"\nJumlah Nilai CekBox \t :"+fieldJumlah.getText());
        }else{
            fieldPil2.setText("");
            fieldJumlah.setText("");
        }
    }//GEN-LAST:event_box2Pil2ActionPerformed

    private void radioData1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioData1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioData1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioCekbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioCekbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioCekbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioCekbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioCekbox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaHasil;
    private javax.swing.JCheckBox box2Pil2;
    private javax.swing.JCheckBox boxPil1;
    private javax.swing.ButtonGroup btnGroupData;
    private javax.swing.ButtonGroup btnGroupPilihan;
    private javax.swing.JButton btnProcess;
    private javax.swing.JTextField fieldHasil;
    private javax.swing.JTextField fieldJumlah;
    private javax.swing.JTextField fieldPil1;
    private javax.swing.JTextField fieldPil2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioData1;
    private javax.swing.JRadioButton radioData2;
    private javax.swing.JRadioButton radioData3;
    private javax.swing.JRadioButton radioPilihan1;
    private javax.swing.JRadioButton radioPilihan2;
    private javax.swing.JRadioButton radioPilihan3;
    // End of variables declaration//GEN-END:variables
}
