/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meeting9T;

/**
 *
 * @author user
 */
public class FormInput extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormInput
     */
    public FormInput() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fieldNama = new javax.swing.JTextField();
        fieldNim = new javax.swing.JTextField();
        comboJurusan = new javax.swing.JComboBox<>();
        comboShift = new javax.swing.JComboBox<>();
        fielBiaya = new javax.swing.JTextField();
        fieldNilai1 = new javax.swing.JTextField();
        fieldNilai2 = new javax.swing.JTextField();
        fieldHasil = new javax.swing.JTextField();
        fieldGrade = new javax.swing.JTextField();
        btnProcess = new javax.swing.JButton();
        btnCleas = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Input"));

        jLabel1.setText("Nama");

        jLabel2.setText("Nim");

        jLabel3.setText("Jurusan");

        jLabel4.setText("SHIFT");

        jLabel5.setText("Biaya/Bln");

        jLabel6.setText("Grade");

        jLabel7.setText("Hasil");

        jLabel8.setText("Nilai 2");

        jLabel9.setText("Nilai 1");

        comboJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "==Jurusan==", "Teknik Infromatika", "Elektro", "Sastra" }));
        comboJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJurusanActionPerformed(evt);
            }
        });

        comboShift.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "==Shift==", "Reg A", "Reg B", "Reg C" }));
        comboShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboShiftActionPerformed(evt);
            }
        });

        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        btnCleas.setText("Clear");
        btnCleas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldNim)
                                    .addComponent(comboJurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboShift, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fielBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(43, 43, 43)
                                .addComponent(fieldGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(37, 37, 37)
                                .addComponent(fieldNilai1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldNilai2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(279, 279, 279)
                                .addComponent(btnCleas, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnProcess))))
                .addGap(0, 620, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(fieldNilai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(fieldNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(fieldNilai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(fieldHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboShift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(fielBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(fieldGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcess)
                    .addComponent(btnCleas))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String Jurusan,Shift,Grade;
    int Nilai1,Nilai2,Hasil,Biaya;
    private void comboJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJurusanActionPerformed
        // TODO add your handling code here:
        if(comboJurusan.getSelectedIndex()==1){
            Jurusan=comboJurusan.getSelectedItem().toString();
        }else if(comboJurusan.getSelectedIndex()==2){
            Jurusan=comboJurusan.getSelectedItem().toString();
        }else if(comboJurusan.getSelectedIndex()==3){
            Jurusan=comboJurusan.getSelectedItem().toString();
        }
    }//GEN-LAST:event_comboJurusanActionPerformed

    private void comboShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboShiftActionPerformed
        // TODO add your handling code here:
        
        if(comboJurusan.getSelectedIndex()==1 && comboShift.getSelectedIndex()==1){
            Biaya=250000;
            fielBiaya.setText(Integer.toString(Biaya));
        }else if(comboJurusan.getSelectedIndex()==1 && comboShift.getSelectedIndex()==2){
            Biaya=250000;
            fielBiaya.setText(Integer.toString(Biaya));
        }else if(comboJurusan.getSelectedIndex()==1 && comboShift.getSelectedIndex()==3){
            Biaya=300000;
            fielBiaya.setText(Integer.toString(Biaya));
        }else if(comboJurusan.getSelectedIndex()==2 && comboShift.getSelectedIndex()==1){
            Biaya=250000;
            fielBiaya.setText(Integer.toString(Biaya));
        }else if(comboJurusan.getSelectedIndex()==2 && comboShift.getSelectedIndex()==2){
            Biaya=250000;
            fielBiaya.setText(Integer.toString(Biaya));
        }else if(comboJurusan.getSelectedIndex()==2 && comboShift.getSelectedIndex()==3){
            Biaya=300000;
            fielBiaya.setText(Integer.toString(Biaya));
        }else if(comboJurusan.getSelectedIndex()==3 && comboShift.getSelectedIndex()==1){
            Biaya=250000;
            fielBiaya.setText(Integer.toString(Biaya));
        }else if(comboJurusan.getSelectedIndex()==3 && comboShift.getSelectedIndex()==2){
            Biaya=250000;
            fielBiaya.setText(Integer.toString(Biaya));
        }else if(comboJurusan.getSelectedIndex()==3 && comboShift.getSelectedIndex()==3){
            Biaya=300000;
            fielBiaya.setText(Integer.toString(Biaya));
        }
    }//GEN-LAST:event_comboShiftActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        Nilai1=Integer.parseInt(fieldNim.getText());
        Nilai2=Integer.parseInt(fieldNilai2.getText());
        
        Hasil=(Nilai1+Nilai2)/2;
        
        if(Hasil<70){
            Grade="D";
            fieldGrade.setText(Grade);
        }else if(Hasil<80){
            Grade="C";
            fieldGrade.setText(Grade);
        }else if(Hasil<90){
            Grade="B";
            fieldGrade.setText(Grade);
        }else if(Hasil<=100){
            Grade="A";
            fieldGrade.setText(Grade);
        }
        fieldHasil.setText(Integer.toString(Hasil));
    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnCleasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleasActionPerformed
        fieldNama.setText("");
        fieldNim.setText("");
        comboJurusan.setSelectedIndex(0);
        comboShift.setSelectedIndex(0);
        fielBiaya.setText("");
        fieldNilai1.setText("");
        fieldNilai2.setText("");
        fieldHasil.setText("");
        fieldGrade.setText("");
    }//GEN-LAST:event_btnCleasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCleas;
    private javax.swing.JButton btnProcess;
    private javax.swing.JComboBox<String> comboJurusan;
    private javax.swing.JComboBox<String> comboShift;
    private javax.swing.JTextField fielBiaya;
    private javax.swing.JTextField fieldGrade;
    private javax.swing.JTextField fieldHasil;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JTextField fieldNilai1;
    private javax.swing.JTextField fieldNilai2;
    private javax.swing.JTextField fieldNim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
