/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meeting9T;

import com.sun.glass.events.KeyEvent;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class PembelianBunga extends javax.swing.JInternalFrame {
    private final DefaultTableModel model;
    /**
     * Creates new form PembelianBunga
     */
    public PembelianBunga() {
        initComponents();
      
        model= (DefaultTableModel) tbBunga.getModel();
        model.getDataVector().removeAllElements();
        tbBunga.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupBayar = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tableBunga = new javax.swing.JScrollPane();
        tbBunga = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        fieldHarga = new javax.swing.JTextField();
        comboBunga = new javax.swing.JComboBox<>();
        fieldJumlahBeli = new javax.swing.JTextField();
        lblBunga = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldTotal = new javax.swing.JTextField();
        radioTunai = new javax.swing.JRadioButton();
        radioKredit = new javax.swing.JRadioButton();
        radioDebit = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        fieldChange = new javax.swing.JTextField();
        boxKirim = new javax.swing.JCheckBox();
        fieldKirim = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldTotalBayar = new javax.swing.JTextField();
        btnProcess = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();

        jLabel1.setText("Nama Bunga");

        tbBunga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Bunga", "Harga/Tangkai", "Jumlah Beli", "Total Bayar"
            }
        ));
        tableBunga.setViewportView(tbBunga);

        jLabel2.setText("Harga/Tangkai");

        comboBunga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Bunga--", "Mawar Biru", "Mawar Merah", "Mawar Putih" }));
        comboBunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBungaActionPerformed(evt);
            }
        });

        fieldJumlahBeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldJumlahBeliKeyReleased(evt);
            }
        });

        jLabel4.setText("Total");

        groupBayar.add(radioTunai);
        radioTunai.setText("Tunai");
        radioTunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTunaiActionPerformed(evt);
            }
        });

        groupBayar.add(radioKredit);
        radioKredit.setText("Kredit");
        radioKredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioKreditActionPerformed(evt);
            }
        });

        groupBayar.add(radioDebit);
        radioDebit.setText("Debit");
        radioDebit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDebitActionPerformed(evt);
            }
        });

        jLabel5.setText("Change");

        boxKirim.setText("KIRIM");
        boxKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxKirimActionPerformed(evt);
            }
        });

        jLabel6.setText("Total Bayar");

        btnProcess.setText("PROCESS");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        jLabel7.setText("Jumlah Beli");

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(radioTunai)
                        .addGap(18, 18, 18)
                        .addComponent(radioKredit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxKirim)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fieldKirim)
                            .addComponent(fieldChange, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProcess))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(fieldTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(radioDebit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBunga, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(fieldJumlahBeli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                .addComponent(fieldTotal, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(18, 18, 18)
                        .addComponent(lblBunga, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(tableBunga, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboBunga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fieldJumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(fieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioTunai)
                                    .addComponent(radioKredit)
                                    .addComponent(radioDebit))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(boxKirim))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fieldChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fieldKirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(btnProcess))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnClear)
                                    .addComponent(fieldTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5))))
                    .addComponent(lblBunga, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(200, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(tableBunga, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String NamaBunga;
    int Harga,JumlahBeli,Total,Kirim;
    double JenisBayar,TotalBayar,change;
   ImageIcon clear = new ImageIcon("");
    private void comboBungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBungaActionPerformed
        if(comboBunga.getSelectedIndex()==1){
            NamaBunga="Mawar Biru";
            Harga=10000;
            fieldHarga.setText(Integer.toString(Harga));
             ImageIcon img = new ImageIcon("src/meeting9T/images/meja.png");
             lblBunga.setIcon(img);
        }else if(comboBunga.getSelectedIndex()==2){
            NamaBunga="Mawar Merah";
            Harga=15000;
            fieldHarga.setText(Integer.toString(Harga));
             ImageIcon img = new ImageIcon("src/meeting9T/images/Stage.png");
             lblBunga.setIcon(img);
        }else if(comboBunga.getSelectedIndex()==3){
            NamaBunga="Mawar Putih";
            Harga=20000;
            fieldHarga.setText(Integer.toString(Harga));
             ImageIcon img = new ImageIcon("src/meeting9T/images/tenda.png");
             lblBunga.setIcon(img);
        }
    }//GEN-LAST:event_comboBungaActionPerformed

    private void fieldJumlahBeliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldJumlahBeliKeyReleased
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           JumlahBeli=Integer.parseInt(fieldJumlahBeli.getText());
           Total=Harga*JumlahBeli;
           fieldTotal.setText(Integer.toString(Total));
       }
    }//GEN-LAST:event_fieldJumlahBeliKeyReleased

    private void radioTunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTunaiActionPerformed
        if(radioTunai.isSelected()){
            JenisBayar=0;
            change=JenisBayar*Total;
            fieldChange.setText(Double.toString(change));
        }
    }//GEN-LAST:event_radioTunaiActionPerformed

    private void radioKreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioKreditActionPerformed
        if(radioKredit.isSelected()){
            JenisBayar=0.3;
            change=JenisBayar*Total;
            fieldChange.setText(Double.toString(change));
        }
    }//GEN-LAST:event_radioKreditActionPerformed

    private void radioDebitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDebitActionPerformed
        if(radioDebit.isSelected()){
            JenisBayar=0.2;
            change=JenisBayar*Total;
            fieldChange.setText(Double.toString(change));
        }
    }//GEN-LAST:event_radioDebitActionPerformed

    private void boxKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxKirimActionPerformed
        if(boxKirim.isSelected()){
            Kirim=5000;
            fieldKirim.setText(Integer.toString(Kirim));
        }else{
            fieldKirim.setText("");
        }
    }//GEN-LAST:event_boxKirimActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        Total=Integer.parseInt(fieldTotal.getText());
        double change=Total*JenisBayar;
        TotalBayar=Total+change+Kirim;
        fieldTotalBayar.setText(Double.toString(TotalBayar));
        Object[] row={NamaBunga,Harga,JumlahBeli,TotalBayar};
        model.addRow(row);
        
        
    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        comboBunga.setSelectedIndex(0);
        fieldHarga.setText("");
        fieldJumlahBeli.setText("");
        fieldTotal.setText("");
        groupBayar.clearSelection();
        fieldChange.setText(title);
        boxKirim.setSelected(false);
        fieldKirim.setText("");
        fieldTotalBayar.setText("");
        lblBunga.setIcon(clear);
        
    }//GEN-LAST:event_btnClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox boxKirim;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnProcess;
    private javax.swing.JComboBox<String> comboBunga;
    private javax.swing.JTextField fieldChange;
    private javax.swing.JTextField fieldHarga;
    private javax.swing.JTextField fieldJumlahBeli;
    private javax.swing.JTextField fieldKirim;
    private javax.swing.JTextField fieldTotal;
    private javax.swing.JTextField fieldTotalBayar;
    private javax.swing.ButtonGroup groupBayar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblBunga;
    private javax.swing.JRadioButton radioDebit;
    private javax.swing.JRadioButton radioKredit;
    private javax.swing.JRadioButton radioTunai;
    private javax.swing.JScrollPane tableBunga;
    private javax.swing.JTable tbBunga;
    // End of variables declaration//GEN-END:variables
}
